# Generated by Django 6.1.1 on 2026-10-03 16:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opis_id', models.PositiveIntegerField(unique=True, verbose_name='OPIS truckstop ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.PositiveIntegerField(verbose_name='rack ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='listed name')),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='price per gallon')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='fuel_route.fuelstation')),
            ],
            options={
                'verbose_name': 'price',
            },
        ),
    ]
