# Generated by Django 6.1.1 on 2026-10-03 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.CharField(max_length=200)),
                ('finish', models.CharField(max_length=200)),
                ('start_label', models.CharField(max_length=255)),
                ('finish_label', models.CharField(max_length=255)),
                ('distance_miles', models.FloatField()),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('times_planned', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_planned_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('start', 'finish'), name='unique_saved_route')],
            },
        ),
    ]
